### ISSUE TITLE
Add impact / outcome to work experience

### ISSUE THREAD

**Issue by SteveBarnett** [ndorfin/cv#14]
These are great, but they'd be more (ahem) impactful if they had an impact. Not just the what, but the why, the impact, the outcome. Who did you help do what? Better, faster, more user-centred?

https://github.com/ndorfin/cv/blob/b116bf61170f344f602d9df86d70a1ca45e9d33b/CV-ShaunO'Connell.html#L209

**Comment by SteveBarnett** [comment]
> This Design System was used in 7 distinct Rails front-ends, and on the company blog. 

is a something like. It could have more "so what?" though.

**Comment by ndorfin** [comment]
Done, thanks!
