### ISSUE TITLE
Reword sentence

### ISSUE THREAD

**Issue by SteveBarnett** [ndorfin/cv#16]
This is doesn't quite read right.

> Together with Sophie Price, and Kah Ho Chan, **I** created Flick's Design System.

or

> Created Flick's Design System with Sophie Price and Kah Ho Chan.

https://github.com/ndorfin/cv/blob/b116bf61170f344f602d9df86d70a1ca45e9d33b/CV-ShaunO'Connell.html#L296

**Comment by ndorfin** [comment]
Done, thanks!
