### ISSUE TITLE
Make first entry more punchy

### ISSUE THREAD

**Issue by SteveBarnett** [ndorfin/cv#17]
This is first in the list, and the longest-running one, so it should be **impressive** 💪 .
Who have you helped (what roles?), and how (faster, better, more collaborative?)?
What kind of sectors, tech stacks?

https://github.com/ndorfin/cv/blob/b116bf61170f344f602d9df86d70a1ca45e9d33b/CV-ShaunO'Connell.html#L214

**Comment by ndorfin** [comment]
Done, thanks!
