### ISSUE TITLE
Add more details to early career

### ISSUE THREAD

**Issue by SteveBarnett** [ndorfin/cv#20]
This one line doesn't feel like enough to cover 15 years!  What did you do? What did you find out about what kind of work you like / dislike?

https://github.com/ndorfin/cv/blob/b116bf61170f344f602d9df86d70a1ca45e9d33b/CV-ShaunO'Connell.html#L352

**Comment by ndorfin** [comment]
I wanted to show an entry point. The next entry contains the 14 years of info :)
